### PR TITLE
500/tab layout

### PR DESCRIPTION
**Pull request by ahmadf0311**

### CODE REVIEW

**Comment by tpachmann** [comment]
I've adjusted the styles a little bit to match the looks of the tags that are already existent in our frontend:
grafik
Other than that, the select box functionality looks good to me - nice work!

**Review by tpachmann — APPROVED** [review]

**Comment by EeveesEyes** [comment]
Please change the target branch

**Review by tpachmann — CHANGES_REQUESTED** [review]
While testing this feature again, I've noticed that the initial tab that is active when loading the page is actually not the tab that is displayed (e.g. on movements, it seems like the "Artworks" tab is selected but the displayed tab is "Timeline").

This should be fixed before releasing this feature - I think it's just the value binding that's missing (see [ng-model](https://docs.angularjs.org/api/ng/directive/select#usage)).

**Review by tpachmann — APPROVED** [review]
Looks good to me, good work!

**Review by tpachmann — APPROVED** [review]
Looks fine - good work!

**Pull request merged**
