### PR TITLE
#561 Tweaked the style of the scrollbar

### PR DESCRIPTION
**Pull request by GiotisK**
issue #561 
Changed the style of slider like how it is shown below.

slider

### CODE REVIEW

**Comment by GiotisK** [comment]
Forgot to mention that i ran "npm install" after cloning the repo because the "ng serve" command didn't work as it was missing some dependecies

**Comment by vinoroidski** [comment]
@GiotisK : 👍 

May I ask from where you saw our project and why you wanted to change the scroll bar? :)

**Comment by GiotisK** [comment]
> @GiotisK : 👍
> 
> May I ask from where you saw our project and why you wanted to change the scroll bar? :)

I found it through the site https://goodfirstissues.com. I want to start contributing to open source projects and I found it a good idea to start from here!

**Comment by EeveesEyes** [comment]
Awesome, thank you :+1:
Two notes: please separate changes to the package-lock.json from features/the code. This makes it easier to track dependency changes. You can prevent changes to the package-lock.json by running `npm ci`. 
And please change the base/target branch to 'staging' as everything there is tested before it gets released.

Nevertheless, your contribution is very much welcome 💯

**Comment by GiotisK** [comment]
> Awesome, thank you 👍
> Two notes: please separate changes to the package-lock.json from features/the code. This makes it easier to track dependency changes. You can prevent changes to the package-lock.json by running `npm ci`.
> And please change the base/target branch to 'staging' as everything there is tested before it gets released.
> 
> Nevertheless, your contribution is very much welcome 💯

Sure. I will look into it asap. If I come across to any problems with these things you mentioned, can I tag you here for possible help? 
Thank you. It will be interesting and fun to contribute in this repo.

**Comment by EeveesEyes** [comment]
> If I come across to any problems with these things you mentioned, can I tag you here for possible help?

Sure, I'm happy to help :)

**Comment by GiotisK** [comment]
I still have some problems understanding the things you mentioned.
Things that I tried to do:
1) I cloned the repo again with the goal of not messing with the package-lock.json
2) I ran ```npm ci``` in the **app** folder but it gives me access rights errors.

**Comment by EeveesEyes** [comment]
I'm not sure why you get access rights errors, can you send the error message?
Maybe you can simply revert your changes to the package-lock.json? There is a dependency to https://github.com/hochschule-darmstadt/ngx-image-viewer , maybe this is a problem?

**Comment by GiotisK** [comment]
> I'm not sure why you get access rights errors, can you send the error message?
> Maybe you can simply revert your changes to the package-lock.json? There is a dependency to https://github.com/hochschule-darmstadt/ngx-image-viewer , maybe this is a problem?

I managed to revert the changes and also changed the base branch to 'staging'. You can check it out and let me know if there is any problem. Thank you for the valuable help!

**Review by EeveesEyes — APPROVED** [review]
Looks nice :+1: 
When deployed, you can see your changes at our [staging server](https://cai-artbrowserstaging.fbi.h-da.de/)

**Pull request merged**
