### PR TITLE
New release of openArtBrowser

### LINKED ISSUE #72: Implement "rank artworks" and other subjects in python
**Is your feature request related to a problem? Please describe.**
We want to replace the JavaScript *_rank.js files with a python solution to be consistent in the ETL programming language and improve extensibility.

**Why do you want this feature? What goals should be achieved**
Reduction of programming languages on backend (All other ETL logic is implemented in Python)

**Describe acceptance criteria**
The existing logic has to work. The rank logic is implemented in python and works.

**What effects does your proposed solution have**
Improve extensibility and only use python within the ETL part.

### LINKED ISSUE #292: Additional artwork attributes
**Reason**
More important information; increases learning effect and fun in using openArtBrowser

**Solution**
The following Wikidata attributes shall be crawled:
main subject (P921) -> main_motif (Hauptmotiv) (HIGH PRIO)
significant event (P793) (MEDIUM PRIO)
exhibition history (P608) (MEDIUM PRIO)

main_motif shall be displayed in artwork page (above motifs). When clicking on main motif chip, a motif component is opened. 
In related artworks, main motif shall be added to the "motif" tab (and, hence, to the all tab)

Significant events and exhibition history (MEDIUM PRIO): 
first check data and provide and discuss concept before start of implementation

**Alternatives**

**Effects**
Main motif gives information about the background of the artwork. 

**Acceptance criteria**

**Additional context**

### LINKED ISSUE #343: Data extraction duplicates due to wikidata redirections
**Describe the bug**
On the elasticsearch server are some motifs that are duplicated because of redirects e. g. Q40446 is redirected from Q1763003, Q14080 is redirected from Q29582371. This has to be filtered so that no redirect ids exist. However it doesn't seem to make a problem for the frontend, i assume the first item of the query result is always taken. Example https://cai-artbrowserstaging.fbi.h-da.de/de/motif/Q14080

**To Reproduce**
When ranking the motifs the program has following output: 
```
this key already exits: Q14080
this key already exits: Q40446
this key already exits: Q40446
Q55387950
Q1763003
Q29582371
Q1763003
Q1763003
Q1763003
Q1763003
Q14631121
Q14631121
```
Which are redirected pages

**Expected behavior**
No duplicates because of redirection.

### LINKED ISSUE #374: Timelines are sometimes not well scaled
**Describe the bug**
On some pages e.g. https://cai-artbrowserstaging.fbi.h-da.de/de/movement/Q37853
The timelines aren't well scaled. A (maybe) wrongly dated artwork distortes the whole timeline so major parts of it are useless.

**To Reproduce**
Open a page in the artbrowser where some entries are statistical outliers

**Expected behavior**
statistical outliers are being ignored (?)

**Screenshots**
grafik

### LINKED ISSUE #394: "more" tab unfolded when opening motif page
**Describe the bug**
When opening a page, the "more" tab should always initially be folded.
For motif pages this is not always the case.

**To Reproduce**
https://openartbrowser.org/de/motif/Q366134

**Expected behavior**

**Additional context**
Fix and check for other pages.

### LINKED ISSUE #409: Include main motifs on the artwork page
**Is your feature request related to a problem? Please describe.**
Issue #292 described changes that would later turn out to be two features with quite different requirements.
This issue shall handle the requirements that only concern the main motifs.

**Why do you want this feature? What goals should be achieved**
Increases the learning effect and fun in using openArtBrowser through the display of new information.

**Describe the solution you'd like**
The main motif attribute, that is already present in the etl process, shall be integrated in an informative way.

**Describe acceptance criteria**
- additional category 'main motif' above the 'motifs' on the artwork page
- integrate main motifs into the `related artworks by motif` tab at the bottom of the artwork page
- add an additional tab for `related artworks by main motif` at the bottom of the artwork page

**What effects does your proposed solution have**
We display the new information, and also allow the user to find artworks that are related to the current artwork by the same main motif (opposed to just any motif displayed in both artworks - which is more concise)

**Additional context**
There have already been pull requests (#347 #336 ) that integrated the first 2 acceptance criteria - the main todo at this point is adding the main motif tab.

### LINKED ISSUE #412: Clickable elements are missing cursor style
**Describe the bug**
On the openartbrowser many elements are clickable. But for some elements there is no indication that they are clickable while being hovered. 
The cursor style should be set to pointer whenever hovering a hyperlink.

**To Reproduce**
1. Go to https://openartbrowser.org/de/artwork/Q23464815
2. Hover over the 'Kunstwerk'-Button
4. See so pointer :(

**Expected behavior**
When hovering an button that acts as a hyperlink the cursour is expected to have the pointer style.

**Screenshots**
grafik
(Kunstwerk Button)
grafik
(Stilrichtung Button)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 77

### LINKED ISSUE #414: Adapt entities-component, change artist life-time
As [required](https://github.com/hochschule-darmstadt/openartbrowser/pull/404#issuecomment-648663438) the artist birth date and death date should be indicated as “1847 – 1922”. Use “*” and “+” only if one of the dates is missing.

Furthermore prevent loading issues from .tif and .tiff thumbnails in the entity-component.

### LINKED ISSUE #426: 'Powered by Wikidata' Footer link
Add the ['powered by wikidata'](https://www.wikidata.org/wiki/Wikidata:Data_access#Best_practices_to_follow) label to the footer bar and link to wikidata.org

### PR DESCRIPTION
**Pull request by jschurse**
For this weeks release the following features have been integrated:

Frontend:
- https://github.com/hochschule-darmstadt/openartbrowser/pull/396: Fixed not well scaled timelines. Fixes #374 
- https://github.com/hochschule-darmstadt/openartbrowser/pull/415: Indicate clickable pills by cursor: pointer. Fixes #412
- https://github.com/hochschule-darmstadt/openartbrowser/pull/418: Read More now always collapsed on page load. Fixes #394 
- https://github.com/hochschule-darmstadt/openartbrowser/pull/416: New artist vita format. Fixes #414
- https://github.com/hochschule-darmstadt/openartbrowser/pull/427: Added Wikidata logo to footer. Fixes #426
- https://github.com/hochschule-darmstadt/openartbrowser/pull/397: Display exhibition history on page. Fixes #292 
- https://github.com/hochschule-darmstadt/openartbrowser/pull/411: New tab for main motives. Fixes #409 

ETL:
- https://github.com/hochschule-darmstadt/openartbrowser/pull/419: Fixed path data_manipulation => data_enhancement in docker env
- https://github.com/hochschule-darmstadt/openartbrowser/pull/405: Crawl of exhibition history. Fixes #292
- https://github.com/hochschule-darmstadt/openartbrowser/pull/421: Avoid redirects for wikidata entities. Fixes #343 and #332
- https://github.com/hochschule-darmstadt/openartbrowser/pull/424: Ranking algorithm now implemented in python. Fixes #72
- https://github.com/hochschule-darmstadt/openartbrowser/pull/413: Remove merge_art_data.js script => replaced with jq command

The version number has been incremented to `1.0.1`

I reserve the right to have overlooked contributions, please notify me if I did!
Please feel free to comment.

### CODE REVIEW

**Comment by BernhardHumm** [comment]
Very good!

A approve all changes. They can go live now.

 

For “Display of exhibition history. #292” I could not find an example. 

E.g., https://cai-artbrowserstaging.fbi.h-da.de/de/artwork/Q12418 does not show an exhibition history.

 

 

------------------------------------

 

 

Von: Jenja Schurse [mailto:notifications@github.com] 
Gesendet: Dienstag, 30. Juni 2020 12:52
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Review requested <review_requested@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] New release of openArtBrowser (#428)

 

For this weeks release the following features have been integrated:

Frontend:

*	#396 <https://github.com/hochschule-darmstadt/openartbrowser/pull/396> : Fixed not well scaled timelines. Fixes #374 <https://github.com/hochschule-darmstadt/openartbrowser/issues/374> 
*	#415 <https://github.com/hochschule-darmstadt/openartbrowser/pull/415> : Indicate clickable pills by cursor: pointer. Fixes #412 <https://github.com/hochschule-darmstadt/openartbrowser/issues/412> 
*	#418 <https://github.com/hochschule-darmstadt/openartbrowser/pull/418> : Read More now always collapsed on page load. Fixes #394 <https://github.com/hochschule-darmstadt/openartbrowser/issues/394> 
*	#416 <https://github.com/hochschule-darmstadt/openartbrowser/pull/416> : New artist vita format. Fixes #414 <https://github.com/hochschule-darmstadt/openartbrowser/issues/414> 
*	#405 <https://github.com/hochschule-darmstadt/openartbrowser/pull/405> : Display of exhibition history. Fixes #292 <https://github.com/hochschule-darmstadt/openartbrowser/issues/292> 
*	#427 <https://github.com/hochschule-darmstadt/openartbrowser/pull/427> : Added Wikidata logo to footer. Fixes #426 <https://github.com/hochschule-darmstadt/openartbrowser/issues/426> 

ETL:

*	#419 <https://github.com/hochschule-darmstadt/openartbrowser/pull/419> : Fixed path data_manipulation => data_enhancement in docker env
*	#421 <https://github.com/hochschule-darmstadt/openartbrowser/pull/421> : Avoid redirects for wikidata entities. Fixes #343 <https://github.com/hochschule-darmstadt/openartbrowser/issues/343>  and #332 <https://github.com/hochschule-darmstadt/openartbrowser/issues/332> 
*	#424 <https://github.com/hochschule-darmstadt/openartbrowser/pull/424> : Ranking algorithm now implemented in python. Fixes #72 <https://github.com/hochschule-darmstadt/openartbrowser/issues/72> 
*	#413 <https://github.com/hochschule-darmstadt/openartbrowser/pull/413> : Remove merge_art_data.js script => replaced with jq command

The version number has been incremented to 1.0.1

I reserve the right to have overlooked contributions, please notify me if I did!
Please feel free to comment.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/hochschule-darmstadt/openartbrowser/pull/428


Commit Summary


*	#374: limit timeline steps to 1000. Use artwork inceptions when time range is bigger
*	#374: Remove artworks from movement timeline which does not fit into the movement time range
*	Displaying artist video before movement videos
*	refactored video-duplication-filter. Displays Artist video before movement videos.
*	#374: Removed debug console output
*	Merge branch 'staging' into improvement/374/fix_bad_scaled_timeline
*	#374: Remove unneeded comments and debug outputs
*	#374: Implement estimate times usage
*	Refactored video component
*	removed unneccessary videoduplication function
*	refactoring of artwork and movement
*	Merge remote-tracking branch 'origin/bugfix/artist_video_order' into bugfix/artist_video_order
*	#412: removed default cursor style from heading pill
*	#414: changed how artist-life-time is displayed. .tif-thumbnails now get replaced by a random non-.tif artwork to prevent loading issues and empty gaps in the entities-component.
*	Merge pull request #396 from hochschule-darmstadt/improvement/374/fix_bad_scaled_timeline
*	#394: removed all calculateCollapseState() methods from entity-pages. (and fixed small translation bug)
*	Set right path to estimate_movement_period script
*	Avoid redirects for wikidata entities
*	Implemented Feedback (Video-Component refactoring)
*	removed console log
*	changed variable names in uniqueVideos-function
*	Merge pull request #419 from hochschule-darmstadt/fix/docker-estimate-movement-period-moved
*	Merge pull request #421 from hochschule-darmstadt/bug/343+332-redirect-problems
*	Merge branch 'staging' into bugfix/artist_video_order
*	Merge pull request #393 from hochschule-darmstadt/bugfix/artist_video_order
*	Merge pull request #415 from hochschule-darmstadt/bug/412/missing_cursor_style
*	Merge branch 'staging' into improvement/394/always_collapse_more
*	Merge pull request #418 from hochschule-darmstadt/improvement/394/always_collapse_more
*	Merge pull request #416 from hochschule-darmstadt/improvement/414/adapt_entities-component
*	Exhibition history
*	Refactor split languages script
*	Merge pull request #405 from hochschule-darmstadt/feature/292-exhibition-history
*	Ranking implemented
*	Remove old ranking scripts + adjust script calls
*	Dockerfile adjusted for ranking
*	Ignore ranks when in input files as attribute
*	Docstrings
*	Filter duplicates from subject lists
*	Avoid duplicates in reference lists
*	Elasticsearch explicitly set type for relativeRank
*	Enable sourceMap for docker config
*	Merge pull request #424 from hochschule-darmstadt/refactoring/72-ranking
*	Remove merge_art_data.js script with jq command
*	Adjusted dockerfile + readme
*	Merge pull request #413 from hochschule-darmstadt/refactoring/merge-art-data
*	#426: added image link to footer.component.html
*	Merge pull request #427 from hochschule-darmstadt/feature/426/wikidata_footer_link
*	Update package.json


File Changes


*	M README.md <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-04c6e90faac2675aa89e2176d2eec7d8>  (2) 
*	M app/angular.json <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-d0177460d8cc2b87066e23e5dd08cc70>  (1) 
*	M app/package.json <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-ac6ee8c82c5d20d9bb9c4d6ac70161d4>  (8) 
*	M app/src/app/core/components/footer/footer.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-29bcecc28062fcfc7827f84b755dbed7>  (5) 
*	M app/src/app/core/components/footer/footer.component.scss <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-81a64debaad9d7a91f46d66b819358a0>  (5) 
*	M app/src/app/pages/artist/artist.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-03810977fbb04411b7edd6824cb47682>  (6) 
*	M app/src/app/pages/artist/artist.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-399be1966843f924fda51f2f05471512>  (61) 
*	M app/src/app/pages/artwork/artwork.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-2a1eca21eadcc4cf8856015bf2b80bd0>  (12) 
*	M app/src/app/pages/artwork/artwork.component.scss <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-300184e2b89ea1379244bb4279adf7ae>  (9) 
*	M app/src/app/pages/artwork/artwork.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-a13c5364d00994dfc65b316eb8fe471b>  (64) 
*	M app/src/app/pages/entities/entities.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-02c4498328ad184481615fdf011ebef2>  (19) 
*	M app/src/app/pages/entities/entities.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-2605d6133213e720a415114f083d8ea5>  (39) 
*	M app/src/app/pages/genre/genre.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-ba21b7b03cf0ee6405f5a11465174451>  (2) 
*	M app/src/app/pages/genre/genre.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-030423b88164726fb3aefb091596efb4>  (23) 
*	M app/src/app/pages/location/location.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-26bf7be1955d41ed84f08647b18a9122>  (2) 
*	M app/src/app/pages/location/location.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-8f2ed05e0564f2d6868ef379d3800069>  (20) 
*	M app/src/app/pages/motif/motif.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-41cf744b1d509b167e1ed4d024c3a7aa>  (2) 
*	M app/src/app/pages/motif/motif.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-824162b3801ae7177dd24b83bc595dca>  (20) 
*	M app/src/app/pages/movement/movement.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-442d7c1e569ba748ad322443da94391b>  (9) 
*	M app/src/app/pages/movement/movement.component.scss <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-de840a3514a7e5bada7741e24df1894f>  (7) 
*	M app/src/app/pages/movement/movement.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-06d3b8d6c1daa6d6493453aac203958e>  (50) 
*	M app/src/app/shared/components/timeline/timeline.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-1f60665f3b76600c6714b8087a06aac5>  (29) 
*	M app/src/app/shared/components/title/title.component.html <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-6c2d693202a63773936dda1744fbbe75>  (2) 
*	M app/src/app/shared/components/video/video.component.ts <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-6aba0e68008628e6ca24a77381a705e2>  (13) 
*	M app/src/locale/messages.de.xlf <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-9df1b77772a89b2d5c15521f6436a005>  (2) 
*	M app/src/styles/entity.scss <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-4d2fc020275a018920deb65b6c8c303d>  (5) 
*	M etl/Dockerfile <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-6110fbfbe79d93a4b6d3419626cdcb9f>  (34) 
*	D etl/data_enhancement/helper.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-17d90e3e3da91a9e6981e2763a69c8a1>  (13) 
*	D etl/data_enhancement/merge_art_data.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-f9c131ff5de6f31913e85d657a335d92>  (106) 
*	D etl/data_enhancement/package.json <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-4cf1d9fff40a90a49bd69c400b4bf8e2>  (20) 
*	A etl/data_enhancement/ranking.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-6cccbac41c443ceb60d2fd2200ac91be>  (120) 
*	D etl/data_enhancement/script_artist_rank.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-daf728b0a80e028214222c301e6d57fe>  (101) 
*	D etl/data_enhancement/script_artworks_rank.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-e7c36b59c9ea7856afd37cb9c8218e67>  (52) 
*	D etl/data_enhancement/script_genres_rank.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-3c2298e853fcd73902785e4c5889401d>  (95) 
*	D etl/data_enhancement/script_locations_rank.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-2179ea12733867302b628193f9b41502>  (95) 
*	D etl/data_enhancement/script_materials_rank.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-f66dd5f53649be35790d0351e3686928>  (95) 
*	D etl/data_enhancement/script_motifs_rank.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-7798da0effeafb15b3469e92609988f1>  (95) 
*	D etl/data_enhancement/script_movements_rank.js <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-87c2c9a1f687c7c2b565f6e83de44515>  (95) 
*	M etl/data_enhancement/split_languages.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-767c6149cb28c83d5ef0c2e8c70451f4>  (194) 
*	M etl/data_extraction/constants.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-c6717f1f133197755075c3cba5d811a0>  (26) 
*	M etl/data_extraction/get_wikidata_items.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-08f266729f9cd7313dd4c237021f3c9d>  (197) 
*	M etl/data_extraction/get_wikipedia_extracts.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-10f770f57027a271fc7b98ab9ef920b1>  (3) 
*	M etl/data_extraction/map_wd_attribute.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-5254e7e90382960d0e76ec24d0a92fe8>  (8) 
*	M etl/data_extraction/map_wd_response.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-815a12f044e9cd04a2c20ebbeee6cb66>  (1) 
*	M etl/scripts/etl.sh <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-81926f95d5e1ed106e7e751614563c55>  (14) 
*	M etl/scripts/run_etl.bat <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-c98610df7dbe365ab704f233d9092e02>  (19) 
*	M etl/shared/constants.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-879164d9ccdb858c338d88bd6521a233>  (25) 
*	M etl/shared/utils.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-f5e9304c97165202763137f9e2ed0aae>  (19) 
*	M etl/upload_to_elasticsearch/elasticsearch_helper.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/428/files#diff-3de81820d89bb0a8cf3bce5486ce4bfe>  (23) 


Patch Links:


*	https://github.com/hochschule-darmstadt/openartbrowser/pull/428.patch
*	https://github.com/hochschule-darmstadt/openartbrowser/pull/428.diff

**Comment by tilomi** [comment]
@BernhardHumm The frontend changes for the exhibition history are still in a pull request #397 which is not merged into staging at the moment. The elasticsearch already provides the exhibition history for the Mona Lisa see https://cai-artbrowserstaging.fbi.h-da.de/api/de/_search?q=id:Q12418

**Comment by BernhardHumm** [comment]
OK and thanks!

 

 

 

------------------------------------

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Dienstag, 30. Juni 2020 15:39
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] New release of openArtBrowser (#428)

 

@BernhardHumm <https://github.com/BernhardHumm>  The frontend changes for the exhibition history are still in a pull request #397 <https://github.com/hochschule-darmstadt/openartbrowser/pull/397>  which is not merged into staging at the moment. The elasticsearch already provides the exhibition history for the Mona Lisa see https://cai-artbrowserstaging.fbi.h-da.de/api/de/_search?q=id:Q12418

**Comment by jschurse** [comment]
#379 has now been merged and can be integrated in this release.
https://cai-artbrowserstaging.fbi.h-da.de/de/artwork/Q12418

**Comment by BernhardHumm** [comment]
Nice!

But the artwork itself should be excluded from related artworks.

 

------------------------------------

 

 

Von: Jenja Schurse [mailto:notifications@github.com] 
Gesendet: Dienstag, 30. Juni 2020 19:28
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] New release of openArtBrowser (#428)

 

#411 <https://github.com/hochschule-darmstadt/openartbrowser/pull/411>  has also been merged (Main Motif tab's) and can bee seen here:
https://cai-artbrowserstaging.fbi.h-da.de/de/artwork/Q12418

**Pull request merged**
