### PR TITLE
#482 Added translations for search result page

### PR DESCRIPTION
**Pull request by FabioBurillo**
This branch fixes the issue #482.

To fix this issue the text passages had to be annotated for translation.
Additionally they were added to the messages.xlf and the individual translation files (i.e. messages.de.xlf).
There the phrases had to be manually translated.

### CODE REVIEW

**Review by EeveesEyes — CHANGES_REQUESTED** [review]
Looks good so far, but the English translations are missing. Then this should be ready

**Comment by FabioBurillo** [comment]
Oh I missed that.
I just checked and noticed that I cannot see if it is working, because it won't work locally with "npm run start:en". 
It says the server is up, but I can't reach it. Is it on my end only?

**Comment by FabioBurillo** [comment]
Forget the last part :D
Now its working

**Review by EeveesEyes — APPROVED** [review]
:+1:

**Pull request merged**
