### PR TITLE
Upgrade to Angular 8

### PR DESCRIPTION
**Pull request by lbucas**
This required changes to most of the dependencies in package.json. I had to upgrade the node version in Travis to 12.

### CODE REVIEW

**Comment by lbucas** [comment]
There is one warning left in npm install:
`npm WARN axobject-query@2.1.1 requires a peer of eslint@^5 || ^6 but none is installed. You must install peer dependencies yourself.`

I do not know where this comes from.

**Comment by lbucas** [comment]
Adding eslint to the dev dependencies fixed the warning.

**Comment by mxxbe** [comment]
Looks good, but since jenja already opened a rather large PR from staging to production I would like to postpone the merge to keep the PR at the current state. 

Also fixed a small merge conflict

**Comment by jschurse** [comment]
I tested it on  
- Linux:
    - Firefox 70.0.1
    - Google Chrome 78.0.3904.97
- Android 9:
    - Firefox 68.3.0
    - Google Chrome 78.0.3904.108
Without further complications.

I would like to add some other devices to the list, before merging.
@mxxbe @lbucas  Could you tell me what browsers and devices you used?

**Comment by lbucas** [comment]
Using Windows 10, it worked in all those browsers:

- Chrome 78
- Firefox 70
- Edge 44
- IE 11 - not very smooth, but its the same with the current version on openartbrowser.org

**Comment by mxxbe** [comment]
Chrome Version 78.0.3904.108 on Windows 10 and 8.1 :joy: also ran

**Comment by jschurse** [comment]
Okay!
I will merge this. Then the others can test it easily too on their devices.

**Pull request merged**
