### PR TITLE
Bug/enhancement/192/198/200

### PR DESCRIPTION
**Pull request by EeveesEyes**
This takes all three issues #192 #198 and #200 into account.

### CODE REVIEW

**Comment by EeveesEyes** [comment]
Some CSS is missing (WIP). Wait for merge please

**Comment by EeveesEyes** [comment]
brute-forced some css, now ready to merge :)

**Comment by jschurse** [comment]
In the meantime some other PR have been merged which leads to merge conflicts. 
@EeveesEyes could you please resolve these conflicts, then this PR can be merged.

**Comment by EeveesEyes** [comment]
> Looks good to me.
> It might just be personal preference but wouldn't it look a little nicer if the youtube button was a little more aligned with the text above and next to it?

I somehow can't reproduce this. Luckily @mauamy can. We are running the same branch, using the same browser in the same version on the same OS with the same Windowmanager on the same device. CSS in a nutshell.

**Pull request merged**
