### PR TITLE
Issue #336 - main subjects

### PR DESCRIPTION
**Pull request by mxxbe**
Currently this looks like this: 

image

We had 2 questions that might need further discussion:
- should we filter out duplicate motifs from the motifs list? 
- is there any suggested label that fits nicer than "Main Subjects"?

### CODE REVIEW

**Comment by tilomi** [comment]
> should we filter out duplicate motifs from the motifs list?
I think this wasn't actually specified within issue #292 , so you have to ask Mr. Humm please.

I think in the PR also misses a requirement, but i'm not too sure (Comment from #292):
> In the related artworks tab “motif”, the main motif shall be added to the motifs (and hence added to “all”)

**Comment by mxxbe** [comment]
Oh right, it's still missing this requirement, thanks for pointing that out :+1:

**Comment by BernhardHumm** [comment]
Yes, filter out duplicate motifs.

Label: “main motif” (German: “Hauptmotiv”) (singular, although in this one particular case, there are actually two entries

 

 

------------------------------------

 

 

Von: Tilo Michel [mailto:notifications@github.com] 
Gesendet: Mittwoch, 13. Mai 2020 15:00
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Issue #336 - main subjects (#347)

 

should we filter out duplicate motifs from the motifs list?

I think this wasn't actually specified within issue #292 <https://github.com/hochschule-darmstadt/openartbrowser/issues/292>  , so you have to ask Mr. Humm please.

I think in the PR also misses a requirement, but i'm not too sure (Comment from #292 <https://github.com/hochschule-darmstadt/openartbrowser/issues/292> ):

In the related artworks tab “motif”, the main motif shall be added to the motifs (and hence added to “all”)

**Comment by jschurse** [comment]
> Oh right, it's still missing this requirement, thanks for pointing that out +1

@mxxbe Any update on that?

**Comment by mxxbe** [comment]
@jschurse yep, it can be reviewed now 👍

**Pull request merged**
