### PR TITLE
Enhancement/84 - Basic page tracking via Google Analytics

### PR DESCRIPTION
**Pull request by lbucas**
I used the Angulartics2 module, which acts as wrapper for different usage analytics services. It is used with G-Anayltics right now, but this could be easily changed in the future. The data privacy statement was updated accordingly.

Use https://analytics.google.com/ to check the usage data. Credential data can be found in the implementation folder in our NextCloud. There is a property each for prod and test.

### CODE REVIEW

**Comment by EeveesEyes** [comment]
I'm actually not sure if we should use google analytics at all. It seems easy but i have concerns about handling of dsgvo (which requires a opt-out) and information disclosure to google. There has to be an open source solution for this.

**Comment by mauamy** [comment]
It would interesting to know, which and how many data google collects and if it is possible to prevent this. If we can not prevent this, I think it would be better to find a F(OSS) solution. 

And as far as I remember we decided to use F(OSS) throughout the whole project, so using google-analytics would break this paradigm anyway.

**Comment by lbucas** [comment]
I'll have a look into the other vendors supported by Angulartics2. Maybe there is a more trustworthy one.

**Comment by lbucas** [comment]
This data is sent in the tracking Http requets:

image

I also added the 'anonymizeIp' setting in the latest commit.

According to this [guide](https://www.datenschutzbeauftragter-info.de/fachbeitraege/google-analytics-datenschutzkonform-einsetzen/), you need the consent of the user to track his/her behavior. This would also apply to other analytics vendors.

**Comment by lbucas** [comment]
I checked the other providers of Angulartics2. 
Piwik (which is now [matomo](https://github.com/matomo-org/matomo)) would be an open source alternative. The downside is, that we would have to host it on our own in order to use it for free.

**Comment by jschurse** [comment]
This would be an opensource platform we could self host:
https://matomo.org/

Let's discuss this tomorrow in plenary

**Comment by lbucas** [comment]
We close this pull request for now and I will change the code for the usage of matomo.

**Pull request closed without merging**
