### PR TITLE
Refactored complete Branch 12

### PR DESCRIPTION
**Pull request by dernicolas**

### CODE REVIEW

**Comment by jschurse** [comment]
On some pages the videos won't load:
eg:
/movement/Q4692
/artwork/Q12418

**Comment by jschurse** [comment]
I updated the youtube_videos.csv and removed the duplicates.
After the next crawl this problem should be solved.

**Comment by lbucas** [comment]
@jschurse It is possible to check if the Video-IDs are still valid during ETL with the YouTube API. If desired, I can add this enhancement.

**Comment by BernhardHumm** [comment]
No, this will not help. The Link could still be broken.

The check must be made in the front-end. If the link is broken then no video frame must be displayed (a similar check is done before displaying an image in the carousel)

 

           Bernhard Humm

 

 

Von: Lucas Bergmann [mailto:notifications@github.com] 
Gesendet: Donnerstag, 28. November 2019 17:24
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Refactored complete Branch 12 (#91)

 

@jschurse <https://github.com/jschurse>  It is possible to check if the Video-IDs are still valid during ETL with the YouTube API. If desired, I can add this enhancement.

**Comment by lbucas** [comment]
I created a new issue: #93. Lets move the discussion there.

**Pull request merged**
