### PR TITLE
Matomo integration

### PR DESCRIPTION
**Pull request by lbucas**
This integrates usage tracking via our self hosted matomo instance. I used the Angulartics2 module, which acts as a wrapper for the matomo tracking functions. The data privacy statement is updated and all possible data privacy measures are taken (no cookies, IP anonymization).

### CODE REVIEW

**Comment by lbucas** [comment]
For local testing you have to enable the tracking in evironment.ts. Go to https://openartbrowser.org/api/analytics/ and select the 'Local testing' property.

**Comment by lbucas** [comment]
@jschurse @BernhardHumm I was not sure about this setting. What do you think?

image

**Comment by BernhardHumm** [comment]
What’s wrong with the standard setting?

The language used seems to be relevant for openArtBrowser’s language selection.

 

 

           Bernhard Humm

 

------------------------------------

 

 

Von: Lucas Bergmann [mailto:notifications@github.com] 
Gesendet: Montag, 16. Dezember 2019 21:13
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Matomo integration (#175)

 

@jschurse <https://github.com/jschurse>  @BernhardHumm <https://github.com/BernhardHumm>  I was not sure about this setting. What do you think?

 <https://user-images.githubusercontent.com/32192444/70939548-bedb5200-2048-11ea-9088-f8066671d23b.png>

**Comment by lbucas** [comment]
@BernhardHumm There is nothing wrong with the standart setting. The question is how detailed you want to track the users location. 

With the standard setting, we would only save the user's country based on the browser's language setting. I think that is sufficient, because it lets us check if we provide all the needed languages.

If the other setting is selected, the IP address would be used to find the location. This would show you the location down to the user's city. I do not think this is necessary, because we do not really need this information and we would have to process the IP through an external API, which seems like a data privacy issue.

**Comment by BernhardHumm** [comment]
I agree (standard setting is sufficient)

 

           Bernhard Humm

 

------------------------------------

 

Von: Lucas Bergmann [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. Dezember 2019 10:43
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Matomo integration (#175)

 

@BernhardHumm <https://github.com/BernhardHumm>  There is nothing wrong with the standart setting. The question is how detailed you want to track the users location.

With the standard setting, we would only save the user's country based on the browser's language setting. I think that is sufficient, because it lets us check if we provide all the needed languages.

If the other setting is selected, the IP address would be used to find the location. This would show you the location down to the user's city. I do not think this is necessary, because we do not really need this information and we would have to process the IP through an external API, which seems like a data privacy issue.

**Comment by jschurse** [comment]
> For local testing you have to enable the tracking in `evironment.ts.` Go to https://openartbrowser.org/api/analytics/ and select the 'Local testing' property.

I just wanted to say that it's not working, then I noticed my adblocker just removed the tracking form the page :D

Nice feature it seems to be working as expected!

**Comment by lbucas** [comment]
@jschurse I had this problem too during development and i took way to long until I figured it out :D 

Please check if it works on the staging server once it is fully deployed.

**Comment by jschurse** [comment]
I had to make an additional fix: https://github.com/hochschule-darmstadt/openartbrowser/commit/5a932eb3b8c95cb2be1b35c19f9e5d9e05470897 but now it's up and running :)

**Pull request merged**
