### PR TITLE
#417 rebuilds countEntityItems() query using bodybuilder which could fix the issue

### PR DESCRIPTION
**Pull request by SpaceDave42**
The number of entities is missing in the staging and live versions of the OAB. This issue was not present if the application was run locally.

The query executed to count all items of a given EntityType was a manual elasticsearch query.
The query is now reqritten using bodybuilder. Locally this query works (as did the previous one). To test if this fixes the issue this fix has to be incorporated in the staging environment as the bug is only apparent there.

### CODE REVIEW

**Review by EeveesEyes — CHANGES_REQUESTED** [review]
I think i found the issue with this. Actually the `entities.component` creates the fetching list options, where the `queryCount` is a promise. This is input for the fetching list, where it gets resolved to a number. But because it is no [two-way-binding](https://angular.io/guide/two-way-binding), the number doesn't get propagated back to the parent component (entites.comp). I would suggest to try to implement a two-way-binding for the fl options.

**Comment by SpaceDave42** [comment]
f21dd37 intends to add the mentioned two way binding between the entities component and the fetching list. This encompasses event emitters in the fetching list on init and on update and an options variable in the entities component to store the information following [this](https://www.netjstech.com/2020/06/angular-custom-two-way-data-binding.html) angular two-way-binding tutorial.

**Review by EeveesEyes — CHANGES_REQUESTED** [review]
This works, when starting the application without localization, but the number of artworks disappears when viewing it in any language.

**Comment by SpaceDave42** [comment]
9977049 Fixes the translation issue. It was caused by the translation engine replacing the content of the span containing the "All X" of "All X Artists" with the translated version ob "All" omitting the number. Splitting the title into 3 seperate spans: "All", "X" and "Artists" fixes this.

**Review by EeveesEyes — APPROVED** [review]
Looks good :+1:

**Pull request merged**
