### PR TITLE
Enhancement/93 detect broken yt links

### PR DESCRIPTION
**Pull request by lbucas**
I integrated requests to the YouTube API in ETL, which check if the video IDs in the CSV are broken.

### CODE REVIEW

**Comment by lbucas** [comment]
Maybe someone has a better idea on how to get the Google developer key, instead of having it in TXT file on the server.

**Comment by BernhardHumm** [comment]
As I stated before, this is not sufficient since between ETL and usage, the link could be broken.

The check must be done in the client. If the link is broken, no video frame must be displayed.

 

           Bernhard Humm

 

 

 

Von: Lucas Bergmann [mailto:notifications@github.com] 
Gesendet: Donnerstag, 28. November 2019 20:20
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Enhancement/93 detect broken yt links (#94)

 

I integrated requests to the YouTube API in ETL, which check if the video IDs in the CSV are broken.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/hochschule-darmstadt/openartbrowser/pull/94


Commit Summary


*	Added broken link id for youtube videos in ETL
*	Small fixes in the yt videos csv


File Changes


*	M scripts/data_manipulation/script_add_youtube_videos.py <https://github.com/hochschule-darmstadt/openartbrowser/pull/94/files#diff-0>  (37) 
*	M scripts/data_manipulation/youtube_videos.csv <https://github.com/hochschule-darmstadt/openartbrowser/pull/94/files#diff-1>  (4) 


Patch Links:


*	https://github.com/hochschule-darmstadt/openartbrowser/pull/94.patch
*	https://github.com/hochschule-darmstadt/openartbrowser/pull/94.diff

**Comment by lbucas** [comment]
We can implement a check in the frontend, but as I stated [here](https://github.com/hochschule-darmstadt/openartbrowser/issues/93#issuecomment-559564341), Youtube embed links with broken IDs still work. You cannot tell if the video works, until the play button is clicked.

I found [this approach](https://gist.github.com/tonY1883/a3b85925081688de569b779b4657439b), which loads the preview picture of the video. A broken ID can then be detected because a broken viedeo's preview picture has a fixed pixel width, which is smaller than the pictures from working videos. We can implement this too, but is hacky and not guaranteed to work in the future.

**Comment by lbucas** [comment]
@jschurse what is your opinion on that?

**Comment by jschurse** [comment]
Instead of checking for the width of the image we should test for the HTTP Status Code.
If the image is not being found an `404 Not Found` is being returned.
Otherwise an `200 OK` (or if you already did this call an `304 Not Modified`) is being returned.

The only problem would be if youtube changed the endpoint for the default thumbnail. Then all calls would return an 404 Error and we wouldn't display any video anymore.
To avoid this I would propose to implement a testcase which calls the endpoint for one specific video which we know exists and asserts the `200 OK` response code.

**Pull request merged**
