### PR TITLE
New Version of OpenArtBrowser

### PR DESCRIPTION
**Pull request by jschurse**
In this new release of the openArtBrowser the following changes are incorporated. 

Frontend:
+ New movement overview on startpage https://github.com/hochschule-darmstadt/openartbrowser/pull/368
+ Display correct number of artworks https://github.com/hochschule-darmstadt/openartbrowser/pull/376
+ artists are now better sorted into the timeline https://github.com/hochschule-darmstadt/openartbrowser/pull/382
+ start_time_est now used by movement component https://github.com/hochschule-darmstadt/openartbrowser/pull/383
+ New Entity pages for all types of data (artists, movements, motifs, etc.) https://github.com/hochschule-darmstadt/openartbrowser/pull/385
+ new tooltips for the openArtBrowser https://github.com/hochschule-darmstadt/openartbrowser/pull/391
+ videos are now displayed next to each other https://github.com/hochschule-darmstadt/openartbrowser/pull/392

ETL:
+ RDF export now contains size, has_part, main_motifs and more https://github.com/hochschule-darmstadt/openartbrowser/pull/390
+ ETL is now capable of transitive search https://github.com/hochschule-darmstadt/openartbrowser/pull/398
+ ETL now resolves transitive partof haspart relationships of movements https://github.com/hochschule-darmstadt/openartbrowser/pull/401
+ ETL now estimates movement periods https://github.com/hochschule-darmstadt/openartbrowser/pull/403

Development:
+ Added console warnings https://github.com/hochschule-darmstadt/openartbrowser/pull/378
+ added new documentation to ETL and refactorings https://github.com/hochschule-darmstadt/openartbrowser/pull/384
+ Refactored crawler data_mainpulation => data_enhancement https://github.com/hochschule-darmstadt/openartbrowser/pull/388

Fixes:
+ Translated Iconclass labels https://github.com/hochschule-darmstadt/openartbrowser/pull/377
+ missing colon https://github.com/hochschule-darmstadt/openartbrowser/pull/379
+ location web / country display fix https://github.com/hochschule-darmstadt/openartbrowser/pull/387
+ percentage encoding in rdf generation https://github.com/hochschule-darmstadt/openartbrowser/pull/395
+ fix display of sizes with unit https://github.com/hochschule-darmstadt/openartbrowser/pull/399

I reserve the right to have overlooked contributions, please notify me if I did!
Please feel free to comment.

### CODE REVIEW

**Comment by jschurse** [comment]
@tilomi what version of the crawl is currently on the master?
Do we need an update before this release?

**Comment by tilomi** [comment]
@jschurse yes i think so the start_time_est, end_time_est + the new has_part, part_of movements are missing

**Comment by jschurse** [comment]
Do think we can update this before Thursday?

**Comment by tilomi** [comment]
The elasticsearch was updated today, if everything works on the staging server we could update.

**Comment by mxxbe** [comment]
Good evening @BernhardHumm, this release is ready to go live from the point of view of the maintainers (frontend and backend). 

Please have a look at the current state of the staging server https://cai-artbrowserstaging.fbi.h-da.de/de/ and approve or request some last minute changes (see detailed release notes above).

If possible, we would like to release the new version tomorrow around 18:00, so we can use the live state for the demonstration on thursday morning.

**Comment by tilomi** [comment]
I merged a ranking fix for the js file after @EeveesEyes told me what the problem was. I let it run on the server now so the ranking should be the same as before.

**Comment by BernhardHumm** [comment]
Thank you. Great progress!

 

Here are my comments:

1.       Start page: „Impressionism“ wrong starting time due to inception typo in one artwork

2.       All artists: Indicate birthdate and death date as “1847 – 1922”, Use “*” and “+” only if one of the dates is missing. 

3.       Related movements: include transitive closure of all super movements and submovements. 
Allow navigation to other movement like on start page.

4.       All motifs: empty rectangle between “Beard” and “John the Baptist” (see screenshot below)

 

All my comments can be resolved later (prio medium); Bug Impressionism should be fixed soon (prio high)

 

P.S. Next time, please indicate which new features I should review. 

 

 



 

------------------------------------

 

 

Von: Maximilian Belling [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. Juni 2020 19:01
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] New Version of OpenArtBrowser (#404)

 

Good evening @BernhardHumm <https://github.com/BernhardHumm> , this release is ready to go live from the point of view of the maintainers (frontend and backend).

Please have a look at the current state of the staging server https://cai-artbrowserstaging.fbi.h-da.de/de/ and approve or request some last minute changes (see detailed release notes above).

If possible, we would like to release the new version tomorrow around 18:00, so we can use the live state for the demonstration on thursday morning.

**Comment by EeveesEyes** [comment]
>  1. Start page: „Impressionism“ wrong starting time due to inception typo in one 

A new crawling should fix this, so this does not block the merge of this PR.

2-4 should be postponed and fixed by the next release, especially 3.

**Comment by jschurse** [comment]
@tilomi @mxxbe Github won´t let me merge this since I updated the version in package.json since your last review :(

**Pull request merged**
