### PR TITLE
multilanguage backend changes from issues #20 and #32

### PR DESCRIPTION
**Pull request by BaderChouaib**
Aims to add multilanguage support to the backend site. 
Part of the changes are:
-ArtOntologyCrawler.py : Pull and integrate language specific data into the .csv and .json files
-requirements.txt : usage of simplejson to enable json parsing of DECIMAL values

New files are:
+languageconfig.csv : Configuration file that contains supported languages for application
+split_languages.py : Splits the master json file after creation into several language files used by elastic_helper.py. Also fills language gaps in data (referenced by #70).
+language_helper.py : Helper class for multilanguage utility functions
+languageconfig.csv : Contains defined languages. Will be loaded by language functions to extract data from wikidata into .json files

### CODE REVIEW

**Comment by tilomi** [comment]
Please first merge staging into your branch

**Comment by BaderChouaib** [comment]
@tilomi wird erledigt

**Comment by jschurse** [comment]
We will merge this after the Wikidata Abstract Changes #11 have been merged and stabilized.

**Comment by BaderChouaib** [comment]
Update (26.11.2019): Branch is ready for staging merge. Remote staging branch was already merged into it

**Comment by xcaverxiii** [comment]
> There are too many changes from the frontend in this pull request. Please remove all files regarding the frontend (all files located in app/ ) from this pull request, otherwise the frontend on the staging server won't be working anymore. They should be pushed with another pull request when the crawl was done and the new indices exist.

@BaderChouaib 
You can remove all frontend changes, these can easily restored from the branche integration/multilanguage branche. 
Just be careful that the deletion of these files in this branche have no influence on the later merge of integration/multilanguage branche branche.

**Comment by BaderChouaib** [comment]
This pull request is outdated, can be closed and will be replaced by #78, mostly because the target branch changed. 
Reason: The state of multilanguage_backend was in a state suggested by #48 which differs from the requirements for testing the branch on staging (isolation between frontend and backend changes). 
This procedure was discussed and planned with @tilomi, since multilanguage_backend was in a state that makes it exceedingly difficult to extract pure backend code from pure frontend code

**Pull request closed without merging**
